export const headings = [
  'Registration No.',
  'Title',
  'Project Type',
  'Country',
  'Report',
  'Methodology',
  'Standard',
  'Status',
]

export const data = [
  {
    title: 'BK Energia Itacoatiara Project',
    projectType: 'Energy industries (renewable - / non-renewable sources)',
    country: 'Brazil',
    methodology: 'AMS-I.D. ver. 6 AMS-III.E. ver. 6',
    standard: 'CDM',
    status: 'Registered',
    ref: '0168',
    pdfLoc: require('../../assets/helpPagePDFs/bk-energia.pdf'),
  },
  {
    title:
      'Catalytic N2O destruction project in the tail gas of the nitric acid plant PANNA 3 of Enaex S.A.',
    projectType: 'Chemical industries',
    country: 'Chile',
    methodology: 'AM0028 ver. 4',
    standard: 'CDM',
    status: 'Registered',
    ref: '1229',
    pdfLoc: require('../../assets/helpPagePDFs/catalytic-n2o.pdf'),
  },
  {
    title: 'Assisted Natural Regeneration of Degraded Lands in Albania',
    projectType: 'Afforestation and reforestation',
    country: 'Albania',
    methodology: 'AR-AM0003 ver. 4',
    standard: 'CDM',
    status: 'Registered',
    ref: '2714',
    pdfLoc: require('../../assets/helpPagePDFs/assisted-natural.pdf'),
  },
  {
    title: 'Trueno River Hydroelectric Power Plant',
    projectType: 'Energy industries (renewable - / non-renewable sources)',
    country: 'Brazil',
    methodology: 'AMS-I.D. ver. 15',
    standard: 'CDM',
    status: 'Registered',
    ref: '4337',
    pdfLoc: require('../../assets/helpPagePDFs/trueno-river.pdf'),
  },
  {
    title:
      '3.66 MW poultry litter based power generation project by Raus Power in India',
    projectType: 'Energy industries (renewable - / non-renewable sources)',
    country: 'India',
    methodology: 'AMS-I.D. ver. 13, AMS-III.E. ver. 15',
    standard: 'CDM',
    status: 'Registered',
    ref: '2348',
    pdfLoc: require('../../assets/helpPagePDFs/ref_2348.pdf'),
  },
  {
    title:
      'GHG emission reduction by thermal oxidation of HFC 23 at Navin Fluorine International Limited (NFIL), Surat, Gujarat, India',
    projectType:
      'Fugitive emissions from production and consumption of halocarbons and sulphur hexafluoride',
    country: 'India',
    methodology: 'AM0001 ver. 4',
    standard: 'CDM',
    status: 'Registered',
    ref: '0838',
    pdfLoc: require('../../assets/helpPagePDFs/ref_0838.pdf'),
  },
  {
    title:
      'HFC23 Decomposition Project of Zhejiang Juhua Co., Ltd, P. R. China',
    projectType:
      'Fugitive emissions from production and consumption of halocarbons and sulphur hexafluoride',
    country: 'China',
    methodology: 'AM0001 Version 03 - Incineration of HFC 23 Waste Streams',
    standard: 'CDM',
    status: 'Registered',
    ref: '0193',
    pdfLoc: require('../../assets/helpPagePDFs/ref_0193.pdf'),
  },
  {
    title:
      'Facilitating Reforestation for Guangxi Watershed Management in Pearl River Basin',
    projectType: 'Afforestation and reforestation',
    country: 'China',
    methodology: 'AR-AM0001 ver. 2',
    standard: 'CDM',
    status: 'Registered',
    ref: '0547',
    pdfLoc: require('../../assets/helpPagePDFs/ref_0547.pdf'),
  },
  {
    title: 'N2O Emission Reduction in ONSAN, REPUBLIC OF KOREA',
    projectType: 'Chemical industries',
    country: 'REPUBLIC OF KOREA',
    methodology: 'AM0021',
    standard: 'CDM',
    status: 'Registered',
    ref: '0099',
    pdfLoc: require('../../assets/helpPagePDFs/ref_0099.pdf'),
  },
  {
    title: 'Huainan Panyi and Xieqiao Coal Mine Methane Utilization Project',
    projectType: 'Mining/mineral production',
    country: 'China',
    methodology: 'ACM0002 ver. 6, ACM0008 ver. 3',
    standard: 'CDM',
    status: 'Registered',
    ref: '1887',
    pdfLoc: require('../../assets/helpPagePDFs/ref_1887.pdf'),
  },
  {
    title:
      'Replacement of Fossil Fuel by Palm Kernel Shell Biomass in the production of Portland Cement',
    projectType: 'Manufacturing industries',
    country: 'Malaysia',
    methodology: 'ACM0003',
    standard: 'CDM',
    status: 'Registered',
    ref: '247',
    pdfLoc: require('../../assets/helpPagePDFs/ref_247.pdf'),
  },
  {
    title: 'Metro Delhi, India',
    projectType: 'Transport',
    country: 'India',
    methodology: 'ACM0016 ver. 4',
    standard: 'CDM',
    status: 'Registered',
    ref: '4463',
    pdfLoc: require('../../assets/helpPagePDFs/ref_4463.pdf'),
  },
  {
    title:
      'Greenhouse gas (GHG) reduction by implementing energy efficient plough share mixer (PSM) technology in soap manufacturing at Hindustan Lever Limited (HLL), India',
    projectType: 'Energy demand',
    country: 'India',
    methodology: 'AMS-II.C. ver. 8',
    standard: 'CDM',
    status: 'Registered',
    ref: '1188',

    pdfLoc: require('../../assets/helpPagePDFs/ref_1188.pdf'),
  },
  {
    title: 'SF6 Switch at Dead Sea Magnesium',
    projectType:
      'Fugitive emissions from production and consumption of halocarbons and sulphur hexafluoride',
    country: 'Israel',
    methodology: 'AM0065 ver. 2',
    standard: 'CDM',
    status: 'Registered',
    ref: '2414',
    pdfLoc: require('../../assets/helpPagePDFs/ref_2414.pdf'),
  },
  {
    title:
      'Effective utilization of waste heat by installing vacuum pre-concentrator in urea section” at Indo Gulf Fertilisers (A Unit of Aditya Birla Group) Jagdishpur.',
    projectType: 'Energy demand',
    country: 'India',
    methodology: 'AM0018 - Steam optimization systems',
    standard: 'CDM',
    status: 'Registered',
    ref: '1272',
    pdfLoc: require('../../assets/helpPagePDFs/ref_1272.pdf'),
  },
  {
    title: 'Jincheng Sihe Coal Mine CMM Generation Project',
    projectType:
      'Mining/mineral production, Fugitive emissions from fuels (solid, oil and gas)',
    country: 'China',
    methodology:
      'ACM0008 ver. 3 - Consolidated methodology for coal bed methane and coal mine methane capture and use for power (electrical or motive) and heat and/or destruction by flaring',
    standard: 'CDM',
    status: 'Registered',
    ref: '1896',
    pdfLoc: require('../../assets/helpPagePDFs/ref_1896.pdf'),
  },
  {
    title:
      'Reforestation as renewable source of wood supplies for industrial use in Brazil',
    projectType: 'Afforestation and reforestation',
    country: 'Brazil',
    methodology:
      'AR-AM0005 - Afforestation and reforestation project activities implemented for industrial and/or commercial uses, version 1',
    standard: 'CDM',
    status: 'Registered',
    ref: '2569',
    pdfLoc: require('../../assets/helpPagePDFs/ref_2569.pdf'),
  },
  {
    title: 'Hiriya Landfill Project',
    projectType: 'Waste handling and disposal',
    country: 'Israel',
    methodology: 'ACM0001 ver. 2',
    standard: 'CDM',
    status: 'Registered',
    ref: '0147',
    pdfLoc: require('../../assets/helpPagePDFs/ref_0147.pdf'),
  },
  {
    title:
      'Moldova Biomass Heating in Rural Communities (Project Design Document No. 2)',
    projectType: 'Energy demand',
    country: 'Republic of Moldova ',
    methodology: 'AMS-II.E. ver. 6, AMS-III.B. ver. 6',
    standard: 'CDM',
    status: 'Registered',
    ref: '0160',
    pdfLoc: require('../../assets/helpPagePDFs/ref_0160.pdf'),
  },
]

export const projectTypes = [
  'Agriculture',
  'Chemical industries',
  'Construction',
  'Energy distribution',
  'Energy demand',
  'Energy industries (renewable - / non-renewable sources)',
  'Fugitive emissions from fuels (solid, oil and gas)',
  'Fugitive emissions from production and consumption of halocarbons and sulphur hexafluoride',
  'Livestock, enteric fermentation, and manure management',
  'Manufacturing industries',
  'Metal production',
  'Mining/mineral production',
  'Solvent use',
  'Transport',
  'Waste handling and disposal',
  'Afforestation and reforestation',
  'Forestry and Other Land Use',
  'Forest conservation (REDD+)',
  'Blue carbon',
]
